dist: xenial
language: python

matrix:
  fast_finish: true
  include:
    - python: 3.8

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install: poetry install
script: make lint

after_success:
  # Send coverage to coveralls:
  - pip install coveralls
  - pytest --cov=tests/
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
