version: '3'

services:
  api:
    build:
      context: .
    command: gunicorn --bind=0.0.0.0:${FLASK_RUN_PORT} wsgi:app
    ports:
    - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    env_file:
      - .env.prod
    restart: unless-stopped
